### ISSUE TITLE
Support Gardener OpenStack credentials w/reference to cloudprofile

### ISSUE THREAD

**Issue by vasu1124** [gardener/external-dns-management#108]
**What would you like to be added**:
Currently, the DNS controller requires secrets for Designate to be provided as follows:
https://github.com/gardener/external-dns-management/blob/master/examples/20-secret-openstack-credentials.yaml

Gardener in has OpenStack secrets with references to (label) cloudprofile.garden.sapcloud.io/name. Please add support such that Gardener users can directly re-use existing secrets of OpenStack.

**Comment by rfranzke** [comment]
Hm, I can't follow, what's the problem? Just create the secret you mentioned once in your project namespace (https://github.com/gardener/external-dns-management/blob/master/examples/20-secret-openstack-credentials.yaml) and then you can refer to it as often as you want in your shoots' configuration: https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml#L250

Can you explain more?

**Comment by vasu1124** [comment]
Gardener's OpenStack secret looks like this:
```
kind: Secret
apiVersion: v1
data:
  domainName: xx==
  password: xx=
  tenantName: xx==
  username: xx
metadata:
  labels:
    cloudprofile.garden.sapcloud.io/name: myopenstack
  name: myopenstack
```

I need to create an additional secret like https://github.com/gardener/external-dns-management/blob/master/examples/20-secret-openstack-credentials.yaml, even though the information is contained in above reference.
