### ISSUE TITLE
Add lastUpdateTime to status fields

### ISSUE THREAD

**Issue by timuthy** [gardener/external-dns-management#128]
**What would you like to be added**:
As an operator I'd like to see a `lastUpdateTime` timestamp for the status sub resources of `DNSEntry`, `DNSOwner`, `DNSProvider`.

Example for `DNSEntry`:
```
status:
  lastUpdateTime: "2020-10-07T00:16:28Z"
  message: dns entry active
  observedGeneration: 1
  provider: provider-name
  providerType: provider-type
  state: Ready
  targets:
  - 8.8.4.4
  ttl: 600
  zone: xyz
```

The `lastUpdateTime` is only supposed to be updated if the DNS record itself is update or the `state` or `message` changes.

**Why is this needed**:
Exposing a `lastUpdateTime` timestamp provides essential information for troubleshooting.
