### ISSUE TITLE
Add hostname to DNSEntry's status

### ISSUE THREAD

**Issue by mvladev** [gardener/external-dns-management#17]
I could't find any way to clean orphaned records. A simple (yet not fully covering all use-cases) is to add in the status of `DNSEntry` hostname.

Broken behavior scenario:

If I create the following resource

```yaml
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: dns
  namespace: default
spec:
  dnsName: api.foo.com
  ttl: 600
  targets:
  - 8.8.8.8
```

The DNS controller will create `api.foo.com` record.
If DNSEntry controller is down and I update `spec.dnsName` to `baz.foo.com`, then when the controller is back again it'll create `baz.foo.com`, leaving `api.foo.com` record in the limbo.

With `.status.dnsName` the flow can be:

```yaml
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: dns
  namespace: default
spec:
  dnsName: api.foo.com
  ttl: 600
  targets:
  - 8.8.8.8
status:
  dnsName: api.foo.com
```

I update the field `spec.dnsName` to `baz.foo.com`, leading to: 

```yaml
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: dns
  namespace: default
spec:
  dnsName: baz.foo.com
  ttl: 600
  targets:
  - 8.8.8.8
status:
  dnsName: api.foo.com
```

Then the controller should delete the old record and remove it from `.status.dnsName` stopping the current reconciliation: 

```yaml
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: dns
  namespace: default
spec:
  dnsName: baz.foo.com
  ttl: 600
  targets:
  - 8.8.8.8
status:
```

This would trigger another reconciliation which would finally create the correct `baz.foo.com` record and update the status:

```yaml
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: dns
  namespace: default
spec:
  dnsName: baz.foo.com
  ttl: 600
  targets:
  - 8.8.8.8
status:
  dnsName: baz.foo.com
```
