### ISSUE TITLE
How the default DNSProvider should be created?

### ISSUE THREAD

**Issue by kmadac** [gardener/external-dns-management#289]
Hi,

This is not a bug or request, but rather a question. It is not clear to me if default DNSProvider should be create manually or it should be created automatically? I have shoot cluster created via gardener dashboard, where I added DNS secret my-openstack-designate-secret2. Then I added shoot dns extension in Shoot object:

```
  dns:
    domain: psh-mcm12.test.t-sov.live
    providers:
      - primary: true
        secretName: my-openstack-designate-secret2
        type: openstack-designate
  extensions:
    - type: shoot-dns-service
      providerConfig:
        apiVersion: service.dns.extensions.gardener.cloud/v1alpha1
        kind: DNSConfig
        dnsProviderReplication:
          enabled: true
``` 

I would expect that DNSProvider specified in Shoot object will be created automatically, but it is not. Is my expectation correct?

Thanks

**Comment by MartinWeindel** [comment]
For the records: this is more a question for the [shoot-dns-service extension](https://github.com/gardener/gardener-extension-shoot-dns-service)

But back to your question:

> I would expect that DNSProvider specified in Shoot object will be created automatically, but it is not. Is my expectation correct?

Yes, you should see something like
```yaml
  extensions:
    - type: shoot-dns-service
      providerConfig:
        apiVersion: service.dns.extensions.gardener.cloud/v1alpha1
        kind: DNSConfig
        dnsProviderReplication:
          enabled: true
        providers:
          - secretName: shoot-dns-service-my-openstack-designate-secret2
            type: openstack-designate
        syncProvidersFromShootSpecDNS: true
```

The `providerConfig.providers` section is updated by the shoot-dns-service admission controller.
You should check if it is running on the Gardener cluster.
Additionally, there is one important line missing in your snippet: `syncProvidersFromShootSpecDNS: true`
Without this line, the admission controller will not consider changes from the `spec.dns.providers` section.
