### ISSUE TITLE
unable to add CNAME record

### ISSUE THREAD

**Issue by SAPRD2** [gardener/external-dns-management#299]
I am trying to add an amazon ELB hostname as a target for a DNSEntry, but external-dns-management adds it as an A type record instead of a CNAME type record. 
This is my configuration
```
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: external-dns-entry
  namespace: default
spec:
  dnsName: external-dns.com
  ttl: 300
  targets:
  - xxxxxxxxxxxxxxxxxxxxx-xxxxxxxxx.eu-west-1.elb.amazonaws.com
```
How can I add the same as a CNAME record ?

Also, the TTL is always "-"(dash) when viewed in AWS console (route53), even if it is set in the DNSEntry CR like the example above.
