### ISSUE TITLE
how to use HTTP PROXY if my DNS provider is behind proxy from my k8s cluster

### ISSUE THREAD

**Issue by sdputurn** [gardener/external-dns-management#303]
**What would you like to be added**:
Allow some way to use HTTP PROXY to be able to connect dns-provider. 

our infra: 
k8s cluster --> HTTP_PROXY --> DNS provider (openstack designate) 

currently i am trying to add PROXY information to the deployment and even to the provider, but no luck.
**values file**:
```
env:
  - name: NO_PROXY
    value: .consul,.local,10.0.0.0/8,localhost,127.0.0.1,.com
  - name: HTTP_PROXY
    value: http://x.x.x.x:8080
  - name: HTTPS_PROXY
    value: http://x.x.x.x:8080
```

**provider file**:
```
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSProvider
metadata:
  name: openstack
  namespace: cert-manager
spec:
  type: openstack-designate
  secretRef:
    name: dns-credential
  domains:
    include:
    - my-domain.private
  providerConfig:
    proxyUrl: http://x.x.x.x:8080
```

**Why is this needed**:
sometime DNS internal DNS provider are reachable only via a PROXY
