### ISSUE TITLE
alibaba weighted dns entries show not supported error

### ISSUE THREAD

**Issue by tareksha** [gardener/external-dns-management#416]
**What happened**:

I am trying to create weighted dns records in alibaba cloud DNS. however the dns entry resource goes immediately in `Invalid` state and shows this error: _routing policy not supported_

**What you expected to happen**:

A weighted dns record to be created in alicloud dns

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
spec:
  dnsName: mydomain.com
  targets:
  - 1.2.3.4
  routingPolicy:
    parameters:
      weight: "50"
    setIdentifier: abc
    type: weighted
  ttl: 60
status:
  state: Invalid
  message: routing policy not supported
  providerType: alicloud-dns
  # ...
```

**Anything else we need to know**:

**Environment**:
