### ISSUE TITLE
Invalid Configuration - Missing Region error while upgrading from 0.22.1 to 0.23.1

### ISSUE THREAD

**Issue by yacovsekli** [gardener/external-dns-management#429]
**What happened**:
while upgrading from version 0.22.1 to 0.23.1
we got this error in the pod:
```
aws-route53: cannot get hosted zones: operation error Route 53: ListHostedZones, failed to resolve service endpoint, endpoint rule error, Invalid Configuration: Missing Region
```

We have tried adding "AWS_REGION" to the deployment env section and to the secret ref, but it is still not working.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:
we are using *webidentity aws* with role ARN and token

**Environment**:

the env in our deployment:
```
env:
        - name: AWS_ROLE_ARN
          value: arn:aws:iam::12313123123:role/my-role-name
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: /var/run/secrets/aws/serviceaccount/token
```

dns provider:
```
apiVersion: dns.gardener.cloud/v1alpha1
  kind: DNSProvider
  metadata:
    finalizers:
    - dns.gardener.cloud/compound
    generation: 1
    labels:
      owner: ops
    name: ops
    namespace: edge-domains
  spec:
    domains:
      include:
      - my.domain.com
    secretRef:
      name: dns-credentials
      namespace: edge-domains
    type: aws-route53
```

secret ref:
```
apiVersion: v1
data:
  AWS_USE_CREDENTIALS_CHAIN: dHJ1ZQ==
  REGION: ZXUtY2VudHJhbC0x 
kind: Secret
metadata:
  finalizers:
  - dns.gardener.cloud/compound
  name: dns-credentials
  namespace: edge-domains
type: Opaque
```
