### ISSUE TITLE
Status of source DNSEntries is not updated correctly if name length >= 48

### ISSUE THREAD

**Issue by MartinWeindel** [gardener/external-dns-management#432]
**What happened**:
The source controller for DNSEntries created the target DNSEntry correctly, but with a different name scheme.
The status of the DNSEntry is not mirrored back to the origin source entry in some cases.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by MartinWeindel** [comment]
Example:
```yaml
# source DNSEntry
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: dns-proxy-api-e3ae7c9f-a218-4b34-af41-68fc40862d2d
  namespace: ns
spec:
  dnsName: some.example.com
  targets:
  - 1.2.3.4
status:
  observedGeneration: 1
  state: ""
```

Target DNSEntry:
```yaml
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  generateName: dns-proxy-api-e3ae7c9f-a218-4b34-af41-68fc40862d2d-dnsentry-
  name: dns-proxy-api-e3ae7c9f-a218-4b34-af41-68fc40862d2d-dnsentrn2qlj
  namespace: ns
spec:
  dnsName: some.example.com
  targets:
  - 1.2.3.4
status:
  lastUpdateTime: "2025-03-27T13:36:48Z"
  message: dns entry active
  provider: ...
  providerType: aws-route53
  state: Ready
  targets:
  - 1.2.3.4
  zone: ...
```

It looks suspicious that the `generateName` is not the prefix.
