### ISSUE TITLE
Empty target breaks the controller

### ISSUE THREAD

**Issue by mvladev** [gardener/external-dns-management#51]
If one of the `DNSEntry` has an empty `target` record it breaks reconciliation for all `DNSEntries` in the cluster

```yaml
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: internal
spec:
  dnsName: foo.bar
  targets:
  - ""
  ttl: 120
status:
  message: "InvalidChangeBatch: [Invalid Resource Record: FATAL problem: DomainNameEmpty
    (Domain name is empty) encountered with '', Unparseable CNAME encountered, Invalid
    Resource Record: FATAL problem: DomainNameEmpty (Domain name is empty) encountered
    with '', Unparseable CNAME encountered]\n\tstatus code: 400, request id: 7f81ce33-74be-4941-a4f1-244290b4ac6f"
  observedGeneration: 2
  provider: SOME-PROVIDER
  providerType: aws-route53
  state: Error
  targets:
  - ""
  ttl: 120
```

I would recommend to not reconcile such DNS entries until all of their targets are DNS labels / IPv{4|6} addresses.
