### ISSUE TITLE
Errors thrown when converting Route53 CNAME record from weighted routing policy to simple

### ISSUE THREAD

**Issue by yanivNaor9** [gardener/external-dns-management#513]
**What happened**:
When removing the `routingPolicy` section from a `DNSEntry` resource, the "Routing policy" of the DNS record in Route53 should change from "Weighted" to "Simple".
Instead, we sometime get the following error in the DNSEntry status:
```
message: 'operation error Route 53: ChangeResourceRecordSets, https response error
    StatusCode: 400, RequestID: e5156404-5b56-4439-af80-3438ab2c4dcf, InvalidChangeBatch:
    [RRSet with DNS name yanivbyps1.ops.live.pu.ugw.cloud.sap., type CNAME cannot
    be created as other RRSets exist with the same name and type.]'
```
**What you expected to happen**:
The "Routing policy" of the DNS record in Route53 should change from "Weighted" to "Simple".

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a `DNSEntry` resource like the following:
```
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: my-dnsentry
spec:
  dnsName: example.com
  routingPolicy:
    parameters:
      weight: "70"
    setIdentifier: example-id
    type: weighted
  targets:
  - target.com
  ttl: 300
```
2. Wait for the dnsentry to be in `Ready` status.
3. Apply the following change to the same resource (removing the `routingPolicy`):
```
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: my-dnsentry
spec:
  dnsName: example.com
  targets:
  - target.com
  ttl: 300
```
Note: this issue happens sporadically, so the problem might not reproduce on the first try.

**Environment**:
AWS
